# Copyright 2021 Ubuntu
# See LICENSE file for licensing details.

options:
  external_url:
    "type": "string"
    "description": "The FQDN for your GitLab unit"
    "default": !!null ""
  http_port:
    "type": "string"
    "description": "The HTTP port"
    "default": "80"
  tls_secret_name:
    type: string
    description: "The Kubernetes TLS secret resource name."
    default: ""
  ssh_host:
    "type": "string"
    "description": "Override the SSH Hostname"
    "default": !!null ""
  email_from:
    "type": "string"
    "description": "Email address used in the from field in mails send by GitLab"
    "default": !!null ""
  from_email_name:
    "type": "string"
    "description": "The Name Used in the From field"
    "default": !!null ""
  reply_to_email:
    "type": "string"
    "description": "Override the reply to email address"
    "default": !!null ""
  smtp_enable:
    "type": "boolean"
    "description": "Enable SMTP sending"
    "default": !!bool "true"
  smtp_address:
    "type": "string"
    "description": "SMTP Address"
    "default": !!null ""
  smtp_port:
    "type": "string"
    "description": "SMTP Port"
    "default": !!null ""
  smtp_user_name:
    "type": "string"
    "description": "SMTP Username"
    "default": !!null ""
  smtp_password:
    "type": "string"
    "description": "SMTP Password"
    "default": !!null ""
  smtp_domain:
    "type": "string"
    "description": "SMTP Domain"
    "default": !!null ""
  smtp_enable_starttls_auto:
    "type": "boolean"
    "description": "Enable STARTTLS automatically"
    "default": !!bool "true"
  smtp_tls:
    "type": "boolean"
    "description": "SMTP TLS"
    "default": !!bool "false"
